### ISSUE TITLE
GETTING SOME ERRORS

### ISSUE THREAD

**Issue by 3th1cyuk1** [0xJeti/intitools#3]
GetActivities error: json: cannot unmarshal object into Go struct field Activity.activities.newPayoutAmount of type float32

Also not getting any updates on discord :(

**Comment by 0xJeti** [comment]
Hi @3th1cyuk1 

This was introduced by a change in API made by Intigriti to handle multi-currency payouts. 

This was fixed in release v0.3.0.

Update via `go get -v -u github.com/0xJeti/intitools/cmd/inti-activity`
