### ISSUE TITLE
Not able to fetch new activity since the last Intigriti update

### ISSUE THREAD

**Issue by leorac** [0xJeti/intitools#7]
Already spoke with @0xJeti about this, but adding here for tracking purpose.

The tool is no longer able to fetch new activity since the last update, the error is `Cannot find element code`

## Steps to reproduce
```
inti-activity -config .monitor.conf -last 10 -tick 2s
2024/08/05 10:38:55 Starting monitoring with tick 2s
2024/08/05 10:38:58 Cannot find element code
```

**Comment by 0xJeti** [comment]
Intigriti implemented a Recaptcha on login so the script is no longer able to log in automatically.
Repository will be archived.
